### ISSUE TITLE
Is there any page limitations?

### ISSUE THREAD

**Issue by SanjayYDas** [Nagh-DE/GoogleGemini-PDF#3]
i am trying to build a pdf query chat bot using google genai , FAISS and GoogleGenerativeAIEmbeddings. when i give a pdf of 25 page it is showing a error
 ie IndexError: list index out of range
![image](https://github.com/Nagh-DE/GoogleGemini-PDF/assets/90176407/7916f0f6-ded7-46ff-b835-09091fd0b735)

For the reference i Have added a ss

**Comment by Nagh-DE** [comment]
no this issue is not because of number of pages on doc, 25 is too less
