### ISSUE TITLE
Error in faiss::FileIOReader::FileIOReader(const char *) at /Users/runner/work/faiss-wheels/faiss-wheels/faiss/faiss/impl/io.cpp:68: Error: 'f' failed: could not open faiss_index/index.faiss for reading: No such file or directory

### ISSUE THREAD

**Issue by maxosorios** [Nagh-DE/GoogleGemini-PDF#4]
Hi!, I've an error :(!

RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char *) at /Users/runner/work/faiss-wheels/faiss-wheels/faiss/faiss/impl/io.cpp:68: Error: 'f' failed: could not open faiss_index/index.faiss for reading: No such file or directory

**Comment by Nagh-DE** [comment]
did you create the vector index using faiss? share me the image of error for better understanding
